Running GA: Success!
Running MD: Failure!
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    exec('run_{}(args)'.format(state), globals(), locals())
  File "<string>", line 1, in <module>
  File "/Users/obastani/Dropbox (Penn)/Covid19/covid19-data/code_alex/MD.py", line 85, in run_MD
    female_name, female_count = [e.strip() for e in gender_cells[0].split(':')]
ValueError: too many values to unpack (expected 2)
too many values to unpack (expected 2)
Running MI: Failure!
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    exec('run_{}(args)'.format(state), globals(), locals())
  File "<string>", line 1, in <module>
  File "/Users/obastani/Dropbox (Penn)/Covid19/covid19-data/code_alex/MI.py", line 62, in run_MI
    sex_table = soup.find(string=re.compile(r'Cases by Sex')).find_parent('table')
AttributeError: 'NoneType' object has no attribute 'find_parent'
'NoneType' object has no attribute 'find_parent'
Running PA: Success!
Failed states: MD, MI